version: '3.9'
services:

  mempool-electrs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure

    ports:
      - 60001:60001 # Electrum
      - 3001:3001 # HTTP

    entrypoint:
      /bin/electrs
    command: |
      --address-search
      --cookie mempool:mempool
      --db-dir /electrs
      --cors '*'
    volumes:
    - 'electrs_data:/electrs'

volumes:
  electrs_data: