version: '3.9'
services:

  mempool-electrs:
    build:
      context: .
      dockerfile: Dockerfile
      image: scalarorg/electrs
    restart: on-failure

    ports:
      - 60001:60001 # Electrum
      - 3001:3001 # HTTP

    entrypoint:
      /bin/electrs
    env_file:
      - .env
    command: |
      --network "${NETWORK}"
      --daemon-dir "${HOME}"
      --db-dir "${DB_FOLDER}
      --main-loop-delay "${MAIN_LOOP_DELAY}
      --electrum-rpc-addr "${ELECTRUM_RPC_ADDR}"
      --cookie "${rpcuser}:${rpcpassword}"
      --cors '*'
      --magic "${MAGIC}"
      --address-search
      --utxos-limit "${UTXOS_LIMIT}"
      --electrum-txs-limit "${ELECTRUM_TXS_LIMIT}"
      --daemon-rpc-addr "${DAEMON_RPC_ADDR}"
      --jsonrpc-import
      --start-height "${START_HEIGHT}"
      --stop-height "${STOP_HEIGHT}"
      --vault-tag "${VAULT_TAG}"
      --vault-version "${VAULT_VERSION}"
      -vvvv
    volumes:
      - 'electrs_data:/electrs'

volumes:
  electrs_data: